In [1]:
import torchvision.models as models
from torch.nn import Parameter
from util import *
import torch
import torch.nn as nn

In [5]:
weight = Parameter(torch.Tensor(3,4))

In [3]:
input = torch.randn(2,3)

In [4]:
input


tensor([[ 0.1890,  0.9996, -0.1446],
        [ 0.4671,  1.4480, -0.6346]])

In [6]:
support = torch.matmul(input, weight)

In [7]:
support


tensor([[ 1.2612e-44, -2.9955e+28,  0.0000e+00, -2.9955e+28],
        [ 1.8217e-44, -7.4013e+28,  0.0000e+00, -7.4013e+28]],
       grad_fn=<MmBackward>)

In [9]:
Parameter(support)

Parameter containing:
tensor([[ 1.2612e-44, -2.9955e+28,  0.0000e+00, -2.9955e+28],
        [ 1.8217e-44, -7.4013e+28,  0.0000e+00, -7.4013e+28]],
       requires_grad=True)

In [13]:
import numpy as np
Parameter(torch.Tensor(np.identity(4)))

Parameter containing:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], requires_grad=True)