In [1]:
from data_loader import DATA_RAW


In [2]:
dat = DATA_RAW(n_question=1223,
                   seqlen=200, separate_char=',')

In [3]:
data_path = './data/assist2009_raw/skill_builder_data_corrected.csv'

In [4]:
 all_data = dat.get_processed_data(data_path)

Load data from pickle file...
Max step: 1295
Num of skills: 123
Num of students: 4163
/Users/maywzh/Workspace/ji_coursenotes/2021spring/CCNUMaster/exp/chapter3/pytorch_dkvmn-master/data_loader.py:248: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return np.array(students_list), skills, max_steps


In [5]:
all_data

[(array([[  1.,   1.,   2., ...,  31.,  32.,  32.],
         [ 32.,  32.,  32., ...,  47.,  47.,  47.],
         [ 47.,  47.,  47., ...,  59.,  59.,  59.],
         ...,
         [116., 116., 116., ...,   0.,   0.,   0.],
         [116., 116., 116., ...,   0.,   0.,   0.],
         [120., 120., 120., ...,   0.,   0.,   0.]]),
  array([[125., 125., 126., ..., 155.,  32., 156.],
         [156., 156.,  32., ..., 171.,  47., 171.],
         [171., 171., 171., ..., 183., 183., 183.],
         ...,
         [116., 116., 116., ...,   0.,   0.,   0.],
         [116., 116., 116., ...,   0.,   0.,   0.],
         [120., 120., 120., ...,   0.,   0.,   0.]]),
  array([[  1.,   1.,   2., ...,  35.,  35.,  35.],
         [ 35.,  35.,  35., ...,  47.,  48.,  48.],
         [ 48.,  48.,  48., ...,  83.,  84.,  84.],
         ...,
         [100., 100., 100., ...,   0.,   0.,   0.],
         [102., 102., 102., ...,   0.,   0.,   0.],
         [116., 116., 116., ...,   0.,   0.,   0.]]),
  array([[125., 

In [6]:
students,  skills, max_steps= dat.load_raw_data(data_path)

Load data from pickle file...
Max step: 1295
Num of skills: 123
Num of students: 4163


In [7]:
students

, 64525.0], [77.0, 1.0, 64525.0], [77.0, 1.0, 64525.0], [77.0, 1.0, 64525.0], [77.0, 1.0, 64525.0], [77.0, 0.0, 64525.0], [77.0, 1.0, 64525.0], [77.0, 1.0, 64525.0], [77.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 0.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 1.0, 64525.0], [79.0, 0.0, 64525.0], [79.0, 1.0, 64525.0], [80.0, 1.0, 64525.0], [80.0, 0.0, 64525.0], [80.0, 1.0, 64525.0], [80.0, 1.0, 64525.0], [80.0, 1.0, 64525.0], [81.0, 1.0, 64525.0], [81.0, 1.0, 64525.0], [81.0, 1.0, 64525.0], [81.0, 1.0, 64525.0], [81.0, 0.0, 64525.0]

In [2]:
pickle_data = {}
students = {}
students_list = []
skills = []
users_id = []
max_steps = -1
min_steps = float('inf')
features = ['assignment_id', 'assistment_id', 'problem_id', 'user_id', 'original', 'correct', 'attempt_count',
            'ms_first_response',
            'skill_id', 'hint_count', 'hint_total', 'first_action', 'bottom_hint']

selected_features = ['skill_id', 'correct',
                        'user_id', 'ms_first_response', 'attempt_count', 'hint_count']

In [3]:
import pandas as pd
file_name = './data/assist2009_raw/skill_builder_data_corrected.csv'
all_data = pd.read_csv(file_name, encoding='ISO-8859-1')
filtered_data = all_data[features]
filtered_data = filtered_data[filtered_data['ms_first_response'] > 0]
filtered_data = filtered_data.fillna(-1)

/Users/maywzh/.pyenv/versions/3.8.6/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (17) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [4]:
filtered_data

assignment_id  assistment_id  problem_id  user_id  original  correct  \
0              277618          33139       51424    64525         1        1   
1              277618          33150       51435    64525         1        1   
2              220674          33159       51444    70363         1        0   
3              220674          33110       51395    70363         1        1   
4              220674          33196       51481    70363         1        0   
...               ...            ...         ...      ...       ...      ...   
401751         291495          57830      108976    96299         0        1   
401752         291495          57843      109015    96299         0        1   
401753         291503          34577       54060    96299         0        1   
401754         291503          34577       54061    96299         0        1   
401755         291503          34577       54062    96299         0        0   

        attempt_count  ms_first_response  skill_id  hint_count  hint_total  \
0                   1              32454       1.0           0           3   
1                   1               4922       1.0           0           3   
2                   2              25390       1.0           0           3   
3                   1               4859       1.0           0           3   
4                  14              19813       1.0           3           4   
...               ...                ...       ...         ...         ...   
401751              1              38234      -1.0           0           2   
401752              1               6500      -1.0           0           0   
401753              1              18344      -1.0           0           3   
401754              1              12922      -1.0           0           2   
401755              9              36047      -1.0           1           3   

        first_action  bottom_hint  
0                  0         -1.0  
1                  0         -1.0  
2                  0         -1.0  
3                  0         -1.0  
4                  0          0.0  
...              ...          ...  
401751             0         -1.0  
401752             0         -1.0  
401753             0         -1.0  
401754             0         -1.0  
401755             0          0.0  

[401431 rows x 13 columns]

In [7]:
from tqdm import tqdm
for index, row in tqdm(filtered_data.iterrows()):
    if row['skill_id'] == -1:
        continue
    if row['skill_id'] not in skills:
        skills.append(int(row['skill_id']))
    if row['user_id'] not in users_id:
        users_id.append(int(row['user_id']))
    if row['user_id'] in students:
        students[row['user_id']].append(
            row[selected_features].values.tolist())
    else:
        students[row['user_id']] = [
            row[selected_features].values.tolist()]

401431it [02:57, 2265.16it/s] 


In [8]:
students

78039.0, 26136.0, 1.0, 0.0],
  [14.0, 1.0, 78039.0, 75809.0, 1.0, 0.0],
  [14.0, 1.0, 78039.0, 17235.0, 1.0, 0.0],
  [14.0, 1.0, 78039.0, 20578.0, 1.0, 0.0],
  [15.0, 1.0, 78039.0, 63391.0, 1.0, 0.0],
  [15.0, 1.0, 78039.0, 45094.0, 1.0, 0.0],
  [18.0, 1.0, 78039.0, 62819.0, 1.0, 0.0],
  [25.0, 1.0, 78039.0, 41572.0, 1.0, 0.0],
  [47.0, 1.0, 78039.0, 54580.0, 1.0, 0.0],
  [50.0, 1.0, 78039.0, 44985.0, 1.0, 0.0],
  [50.0, 1.0, 78039.0, 39112.0, 1.0, 0.0],
  [50.0, 1.0, 78039.0, 17707.0, 1.0, 0.0],
  [50.0, 1.0, 78039.0, 36676.0, 1.0, 0.0],
  [50.0, 1.0, 78039.0, 48020.0, 1.0, 0.0],
  [50.0, 1.0, 78039.0, 11089.0, 1.0, 0.0],
  [50.0, 1.0, 78039.0, 15015.0, 1.0, 0.0],
  [50.0, 1.0, 78039.0, 10115.0, 1.0, 0.0],
  [64.0, 1.0, 78039.0, 22324.0, 1.0, 0.0],
  [296.0, 1.0, 78039.0, 31406.0, 1.0, 0.0],
  [296.0, 1.0, 78039.0, 35684.0, 1.0, 0.0],
  [296.0, 1.0, 78039.0, 13875.0, 1.0, 0.0],
  [299.0, 0.0, 78039.0, 117777.0, 2.0, 0.0],
  [299.0, 1.0, 78039.0, 150479.0, 1.0, 0.0],
  [299.0, 1.0, 780

In [9]:
    pickle_data = {}

In [11]:
import pickle
pickle_data['students'] = students
pickle_data['skills'] = skills
pickle_data['users_id'] = users_id
pickling_on = open("students.pickle", "wb")
pickle.dump(pickle_data, pickling_on)
pickling_on.close()

In [12]:
for user_id in users_id:
    if len(students[user_id]) > max_steps:
        max_steps = len(students[user_id])
    if len(students[user_id]) < min_steps:
        min_steps = len(students[user_id])
    if len(students[user_id]) <= 2:
        del students[user_id]
    else:
        students_list.append(students[user_id])

In [13]:
print('Max step:', max_steps)
print('Num of skills:', len(skills))
print('Num of students:', len(users_id))
        # np.array([List_s1[[],[],[]],List_s2[[][][]]],...,List_s3[[][]]])
       

Max step: 1295
Num of skills: 123
Num of students: 4163


In [14]:
students_list


  [311.0, 1.0, 78417.0, 34265.0, 1.0, 0.0],
  [311.0, 0.0, 78417.0, 83520.0, 2.0, 0.0],
  [311.0, 0.0, 78417.0, 83401.0, 3.0, 0.0],
  [311.0, 1.0, 78417.0, 68569.0, 1.0, 0.0],
  [311.0, 1.0, 78417.0, 68692.0, 1.0, 0.0],
  [311.0, 0.0, 78417.0, 61163.0, 5.0, 0.0],
  [311.0, 1.0, 78417.0, 166542.0, 1.0, 0.0],
  [311.0, 0.0, 78417.0, 128736.0, 11.0, 1.0],
  [311.0, 1.0, 78417.0, 267663.0, 1.0, 0.0],
  [311.0, 0.0, 78417.0, 106143.0, 8.0, 0.0],
  [311.0, 1.0, 78417.0, 185919.0, 1.0, 0.0],
  [311.0, 1.0, 78417.0, 41975.0, 1.0, 0.0],
  [311.0, 1.0, 78417.0, 132103.0, 1.0, 0.0],
  [311.0, 0.0, 78417.0, 50086.0, 3.0, 0.0],
  [311.0, 1.0, 78417.0, 40599.0, 1.0, 0.0],
  [311.0, 0.0, 78417.0, 108286.0, 2.0, 0.0],
  [311.0, 1.0, 78417.0, 156423.0, 1.0, 0.0],
  [311.0, 0.0, 78417.0, 48590.0, 7.0, 3.0],
  [311.0, 1.0, 78417.0, 23496.0, 1.0, 0.0],
  [311.0, 0.0, 78417.0, 25664.0, 4.0, 0.0],
  [311.0, 1.0, 78417.0, 29792.0, 1.0, 0.0],
  [311.0, 1.0, 78417.0, 23393.0, 1.0, 0.0],
  [311.0, 1.0, 78417.0

In [ ]:
 dat = DATA_RAW(n_question=params.n_question,
                   seqlen=200, separate_char=',')