In [3]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist #Load data

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()


In [18]:
x_train, x_test = x_train / 255.0, x_test / 255.0

array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.0000000

In [6]:
# 建立一个简单的线性堆叠模型
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
# 预测
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.16136265, -0.20569833,  0.40937287,  0.3873847 , -0.01499307,
        -0.49291384, -0.17135404,  0.6987891 ,  0.16324165,  0.31973585]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()


array([[0.09815435, 0.06799813, 0.12578215, 0.12304661, 0.08228473,
        0.0510224 , 0.07037405, 0.16800062, 0.09833895, 0.11499797]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()


2.9754906

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)


Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 2s 27us/sample - loss: 0.2977 - accuracy: 0.9118
Epoch 2/5
60000/60000 [==============================] - 1s 22us/sample - loss: 0.1436 - accuracy: 0.9568
Epoch 3/5
60000/60000 [==============================] - 1s 22us/sample - loss: 0.1087 - accuracy: 0.9663
Epoch 4/5
60000/60000 [==============================] - 1s 22us/sample - loss: 0.0883 - accuracy: 0.9724
Epoch 5/5
60000/60000 [==============================] - 1s 22us/sample - loss: 0.0747 - accuracy: 0.9768


In [12]:
model.evaluate(x_test,  y_test, verbose=2)


10000/10000 - 0s - loss: 0.0720 - accuracy: 0.9781


[0.07198181667551398, 0.9781]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.8614978e-08, 6.4085990e-09, 4.3687373e-06, 5.7192512e-05,
        7.4862720e-12, 2.6368864e-06, 4.7449214e-13, 9.9992013e-01,
        3.2506252e-06, 1.2323407e-05],
       [1.1698964e-06, 1.1071626e-04, 9.9985957e-01, 2.8547836e-05,
        1.6150033e-14, 9.7366204e-09, 3.4654622e-08, 1.9001372e-12,
        2.6944555e-08, 3.3183653e-13],
       [3.6937520e-06, 9.9885571e-01, 3.4959070e-04, 1.8043374e-05,
        2.0696540e-05, 2.5307007e-05, 1.2739586e-05, 3.0676651e-04,
        4.0646121e-04, 8.3756584e-07],
       [9.9961984e-01, 7.1793105e-09, 6.9654714e-05, 8.3819219e-07,
        2.7307410e-06, 4.1559915e-06, 1.4094578e-05, 2.4472183e-04,
        1.4224739e-07, 4.3744512e-05],
       [1.5520221e-06, 5.2794291e-10, 5.9942533e-07, 1.5567620e-07,
        9.9710017e-01, 2.2119627e-06, 6.1759022e-07, 4.8598253e-05,
        5.0087777e-07, 2.8455495e-03]], dtype=float32)>